### ISSUE TITLE
Remove environment from config file, just have one config per file

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#800]
Currently we are grouping multiple sets of independent configs into a single config file. This is a 12-factor anti-pattern:

> In a twelve-factor app, env vars are granular controls, each fully orthogonal to other env vars. They are never grouped together as “environments”, but instead are independently managed for each deploy. This is a model that scales up smoothly as the app naturally expands into more deploys over its lifetime.

Source: https://12factor.net/config

More importantly though, we have seen exactly the issues that the 12-factor principles predict. For example, when switching between different setups (dev, runtime dc, etc.) we have mounted incorrect configs, that all of a sudden had a network configured.

So in essence we should go from

```yaml
environments:
   - name: one-environment
     optionA: bar
     optionB: baz

   - name: a-completely-different-environment
     optionA: bar
     optionB: baz
```

to

```yaml
optionA: foo
optionB: bar
```
